name: NoxetServer
version: '${project.version}'
main: org.noxet.noxetserver.NoxetServer
api-version: 1.19
commands:
  hub:
    description: Go to the hub
    usage: /hub
    aliases:
      - leave
      - lobby
  spawn:
    description: Go to spawn
    usage: /spawn
  smp:
    description: Join the SMP server
    usage: /smp
    aliases:
      - survival
  anarchy:
    description: Join the Anarchy server
    usage: /anarchy
    aliases:
      - anarchy-island
  wild:
    description: Enter the wilderness...
    usage: /wild
    aliases:
      - wilderness
      - rtp
      - touch-grass
  tpa:
    description: Send/accept/deny/cancel a teleportation request to/from a player
    usage: /tpa <player|cancel|accept|deny> [player]
    aliases:
      - tpask