name: NoxetServer
version: '${project.version}'
main: org.noxet.noxetserver.NoxetServer
api-version: 1.19
commands:
  hub:
    description: Go to the hub
    usage: /hub
    aliases:
      - leave
      - lobby
      - l
  spawn:
    description: Go to spawn
    usage: /spawn
  smp:
    description: Join the SMP server
    usage: /smp
    aliases:
      - survival
  anarchy:
    description: Join the Anarchy server
    usage: /anarchy
  wild:
    description: Enter the wilderness...
    usage: /wild
    aliases:
      - wilderness
      - rtp
      - touch-grass
  tpa:
    description: Send/accept/deny/cancel a teleportation request to/from a player
    usage: /tpa <player|cancel|accept|deny> [player|*]
  whereami:
    description: Check what world and realm you are in
    usage: /whereami
  games:
    description: Choose from games to play
    usage: /games
    aliases:
      - play
      - lets-go
  home:
    description: Teleport to/manage homes
    usage: /home <tp|set|remove|list|rename> [home name] [(for rename) new home name]
    aliases:
      - h
  chickenleg:
    description: chicken leg.
    usage: /chickenleg
  doas:
    description: Command impersonation command
    usage: /doas <player> <command> [args...]
  mute:
    description: Mute a player
    usage: /mute <player>
  unmute:
    description: Unmute a player
    usage: /unmute <player>
  msg:
    description: Talk privately to a player
    usage: /msg <player|toggle> [message]
    aliases:
      - message
      - talk
      - tell
      - whisper
      - dm
  togglepreserve:
    description: Toggles a preserved world
    usage: /togglepreserve